version: '3'

services:
  db:
      image: 'mysql:5.7'
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: app
      ports:
        - '3306:3306'
      volumes:
        - db_data:/var/lib/mysql:rw

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db_data:
